[package]
name = "rustboy"
version = "0.1.0"
authors = ["Gil Mendes <gil00mendes@gmail.com>"]

[dependencies]
blip_buf = ">=0.1.3"
clap = "2.30.0"
cpal = "0.2"
log = "0.4"
error-chain = "0.11"
bitflags = "1.0"
nalgebra = "0.14.0"
nom = "^3.2"
